disabled_rules:
  - trailing_newline
  - trailing_whitespace
  - todo
included:
  - SwiftIntro
excluded:
  - Carthage
  - Pods
  - SwiftIntro/Enums/Generated
  - SwiftIntro/HTTP/Request_Extension.swift
line_length: 200
type_name:
  min_length: 4
  max_length:
    warning: 80
    error: 120
type_body_length:
  warning: 300
  error: 400

function_parameter_count:
  warning: 4
  error: 5

function_body_length:
  warning: 15
  error: 20